name: Test
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - run: gofmt -d -s ./cmd/badges

      - run: go build ./cmd/badges
        env:
          GITHUB_TOKEN: ${{ secrets.READ_ALL_REPO_GITHUB_TOKEN }}
